// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../lib/debug.js', ['ssd.debug'], ['goog.debug', 'goog.debug.FancyWindow', 'goog.debug.LogManager', 'goog.debug.Logger']);
goog.addDependency('../../../lib/helpers.js', ['ssd.helpers'], ['goog.array', 'goog.json', 'goog.object']);
